// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanetaryTravelAgency.Models;

namespace PlanetaryTravelAgency.Migrations
{
    [DbContext(typeof(PlanetaryTravelAgencyContext))]
    partial class PlanetaryTravelAgencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PlanetaryTravelAgency.Models.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Radiation")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<string>("Weather")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PlanetId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("PlanetaryTravelAgency.Models.PlanetSpaceship", b =>
                {
                    b.Property<int>("PlanetSpaceshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PlanetId")
                        .HasColumnType("int");

                    b.Property<int>("SpaceshipId")
                        .HasColumnType("int");

                    b.HasKey("PlanetSpaceshipId");

                    b.HasIndex("PlanetId");

                    b.HasIndex("SpaceshipId");

                    b.ToTable("PlanetSpaceship");
                });

            modelBuilder.Entity("PlanetaryTravelAgency.Models.Spaceship", b =>
                {
                    b.Property<int>("SpaceshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SpaceshipId");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("PlanetaryTravelAgency.Models.PlanetSpaceship", b =>
                {
                    b.HasOne("PlanetaryTravelAgency.Models.Planet", "Planet")
                        .WithMany("JoinEntities")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanetaryTravelAgency.Models.Spaceship", "Spaceship")
                        .WithMany("JoinEntities")
                        .HasForeignKey("SpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");

                    b.Navigation("Spaceship");
                });

            modelBuilder.Entity("PlanetaryTravelAgency.Models.Planet", b =>
                {
                    b.Navigation("JoinEntities");
                });

            modelBuilder.Entity("PlanetaryTravelAgency.Models.Spaceship", b =>
                {
                    b.Navigation("JoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
